# Generated by Django 5.0.7 on 2024-07-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barinak',
            fields=[
                ('barinak_id', models.AutoField(db_column='BarinakID', primary_key=True, serialize=False)),
                ('isim', models.CharField(blank=True, db_column='Isim', max_length=255, null=True)),
                ('adres', models.CharField(blank=True, db_column='Adres', max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=15, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=100, null=True)),
            ],
            options={
                'db_table': 'barinak',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hayvan',
            fields=[
                ('hayvan_id', models.AutoField(db_column='HayvanID', primary_key=True, serialize=False)),
                ('isim', models.CharField(blank=True, db_column='Isim', max_length=255, null=True)),
                ('tur', models.CharField(blank=True, db_column='Tur', max_length=50, null=True)),
                ('cins', models.CharField(blank=True, db_column='Cins', max_length=50, null=True)),
                ('cinsiyet', models.CharField(blank=True, db_column='Cinsiyet', max_length=10, null=True)),
                ('yas', models.IntegerField(blank=True, db_column='Yas', null=True)),
                ('saglik_durumu', models.CharField(blank=True, db_column='Saglik_Durumu', max_length=50, null=True)),
                ('sahiplenme_durum', models.CharField(blank=True, db_column='Sahiplenme_Durumu', max_length=50, null=True)),
                ('giris_tarihi', models.DateField(blank=True, db_column='Giris_Tarihi', null=True)),
            ],
            options={
                'db_table': 'hayvan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ilgilenir',
            fields=[
                ('ilgilenir_id', models.AutoField(db_column='IlgilenirId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ilgilenir',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('personel_id', models.AutoField(db_column='PersonelID', primary_key=True, serialize=False)),
                ('isim', models.CharField(blank=True, db_column='Ad', max_length=255, null=True)),
                ('soyisim', models.CharField(blank=True, db_column='Soyad', max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=15, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=100, null=True)),
            ],
            options={
                'db_table': 'personel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sahiplenen',
            fields=[
                ('sahiplenme_id', models.AutoField(db_column='Sahiplenen_ID', primary_key=True, serialize=False)),
                ('isim', models.CharField(blank=True, db_column='Ad', max_length=255, null=True)),
                ('soyisim', models.CharField(blank=True, db_column='Soyad', max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=15, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=100, null=True)),
            ],
            options={
                'db_table': 'sahiplenen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('sponsor_id', models.AutoField(db_column='SponsorID', default=1, primary_key=True, serialize=False)),
                ('isim', models.CharField(blank=True, db_column='Isim', max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=15, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=100, null=True)),
            ],
            options={
                'db_table': 'sponsor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SponsorOldu',
            fields=[
                ('sponsor_id', models.AutoField(db_column='SponsorOlID', primary_key=True, serialize=False)),
                ('bagis_miktari', models.DecimalField(blank=True, db_column='BagisMiktari', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'sponsor_oldu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ziyaretci',
            fields=[
                ('ziyaretci_id', models.AutoField(db_column='ZiyaretciID', primary_key=True, serialize=False)),
                ('isim', models.CharField(blank=True, db_column='Ad', max_length=255, null=True)),
                ('soyisim', models.CharField(blank=True, db_column='Soyad', max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=15, null=True)),
                ('mail', models.CharField(blank=True, db_column='Mail', max_length=100, null=True)),
            ],
            options={
                'db_table': 'ziyaretci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZiyaretEdildi',
            fields=[
                ('ziyaret_id', models.AutoField(db_column='ZiyaretID', primary_key=True, serialize=False)),
                ('ziyaret_tarihi', models.DateField(blank=True, db_column='ZiyaretTarihi', null=True)),
            ],
            options={
                'db_table': 'ziyaret_edildi',
                'managed': False,
            },
        ),
    ]
